server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost:3307/food_ordering?serverTimezone=UTC
  sql:
    init:
      schema-locations: classpath:db/schema-mysql.sql
      data-locations: classpath:db/data-mysql.sql
      platform: mysql
      mode: always
logging:
  level:
    org.quentin.security: trace

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: org.quentin.security.dto